target :'MCWavesExample' do
    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '6.0'
    
    pod 'Masonry', '~> 1.0'
    pod 'MCConstants', '~> 0.0.2'
    pod 'MCCommonTableView', '~> 0.0.1'
end
